require:
  [
    "@babel/register",
    "jsdom-global/register",
    "ts-node/register",
    "test/mocha.config.js",
    "tsconfig.test.json",
  ]
spec: [test/**/*.spec.js, test/**/*.spec.ts, test/**/*.spec.tsx]
